#pragma once
#include <iostream>
#include <vector>
#include <chrono>
#include <tuple>
#include "CTlsPool.h"  
#include "Data.h"

template <typename T>
void comparePerformance(size_t numAllocations) {
    std::vector<double> CTlsPoolDurations;
    std::vector<double> newDeleteDurations;

    CTlsPool<T> CTlsPool(numAllocations);

    auto CTlsPoolStart = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < numAllocations; ++i) {
        T* obj = CTlsPool.allocate();
        CTlsPool.deallocate(obj);
    }
    auto CTlsPoolEnd = std::chrono::high_resolution_clock::now();
    auto CTlsPoolDuration = std::chrono::duration_cast<std::chrono::microseconds>(CTlsPoolEnd - CTlsPoolStart).count();
    CTlsPoolDurations.push_back(CTlsPoolDuration);

    auto newDeleteStart = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < numAllocations; ++i) {
        T* obj = new T;
        delete obj;
    }
    auto newDeleteEnd = std::chrono::high_resolution_clock::now();
    auto newDeleteDuration = std::chrono::duration_cast<std::chrono::microseconds>(newDeleteEnd - newDeleteStart).count();
    newDeleteDurations.push_back(newDeleteDuration);

    // 그래프 그리기
    plt::plot(CTlsPoolDurations, "r-", label = "CTlsPool");
    plt::plot(newDeleteDurations, "k-", label = "new/delete");

    plt::xlabel("Struct Index");
    plt::ylabel("Time (microseconds)");
    plt::title("CTlsPool vs new/delete Performance");
    plt::legend();
    plt::grid(true);

    plt::save("performance_graph.png");
    std::cout << "Graph generated: performance_graph.png\n";
}

void Test()
{
    const size_t numAllocations = 10000;

    comparePerformance<MyStruct0>(numAllocations);
    comparePerformance<MyStruct1>(numAllocations);
    comparePerformance<MyStruct2>(numAllocations);
    comparePerformance<MyStruct3>(numAllocations);
    comparePerformance<MyStruct4>(numAllocations);
    comparePerformance<MyStruct5>(numAllocations);
    comparePerformance<MyStruct6>(numAllocations);
    comparePerformance<MyStruct7>(numAllocations);
    comparePerformance<MyStruct8>(numAllocations);
    comparePerformance<MyStruct9>(numAllocations);
    comparePerformance<MyStruct10>(numAllocations);
    comparePerformance<MyStruct11>(numAllocations);
    comparePerformance<MyStruct12>(numAllocations);
    comparePerformance<MyStruct13>(numAllocations);
    comparePerformance<MyStruct14>(numAllocations);
    comparePerformance<MyStruct15>(numAllocations);
    comparePerformance<MyStruct16>(numAllocations);
    comparePerformance<MyStruct17>(numAllocations);
    comparePerformance<MyStruct18>(numAllocations);
    comparePerformance<MyStruct19>(numAllocations);
    comparePerformance<MyStruct20>(numAllocations);
    comparePerformance<MyStruct21>(numAllocations);
    comparePerformance<MyStruct22>(numAllocations);
    comparePerformance<MyStruct23>(numAllocations);
    comparePerformance<MyStruct24>(numAllocations);
    comparePerformance<MyStruct25>(numAllocations);
    comparePerformance<MyStruct26>(numAllocations);
    comparePerformance<MyStruct27>(numAllocations);
    comparePerformance<MyStruct28>(numAllocations);
    comparePerformance<MyStruct29>(numAllocations);
    comparePerformance<MyStruct30>(numAllocations);
    comparePerformance<MyStruct31>(numAllocations);
    comparePerformance<MyStruct32>(numAllocations);
    comparePerformance<MyStruct33>(numAllocations);
    comparePerformance<MyStruct34>(numAllocations);
    comparePerformance<MyStruct35>(numAllocations);
    comparePerformance<MyStruct36>(numAllocations);
    comparePerformance<MyStruct37>(numAllocations);
    comparePerformance<MyStruct38>(numAllocations);
    comparePerformance<MyStruct39>(numAllocations);
    comparePerformance<MyStruct40>(numAllocations);
    comparePerformance<MyStruct41>(numAllocations);
    comparePerformance<MyStruct42>(numAllocations);
    comparePerformance<MyStruct43>(numAllocations);
    comparePerformance<MyStruct44>(numAllocations);
    comparePerformance<MyStruct45>(numAllocations);
    comparePerformance<MyStruct46>(numAllocations);
    comparePerformance<MyStruct47>(numAllocations);
    comparePerformance<MyStruct48>(numAllocations);
    comparePerformance<MyStruct49>(numAllocations);
    comparePerformance<MyStruct50>(numAllocations);
    comparePerformance<MyStruct51>(numAllocations);
    comparePerformance<MyStruct52>(numAllocations);
    comparePerformance<MyStruct53>(numAllocations);
    comparePerformance<MyStruct54>(numAllocations);
    comparePerformance<MyStruct55>(numAllocations);
    comparePerformance<MyStruct56>(numAllocations);
    comparePerformance<MyStruct57>(numAllocations);
    comparePerformance<MyStruct58>(numAllocations);
    comparePerformance<MyStruct59>(numAllocations);
    comparePerformance<MyStruct60>(numAllocations);
    comparePerformance<MyStruct61>(numAllocations);
    comparePerformance<MyStruct62>(numAllocations);
    comparePerformance<MyStruct63>(numAllocations);
    comparePerformance<MyStruct64>(numAllocations);
    comparePerformance<MyStruct65>(numAllocations);
    comparePerformance<MyStruct66>(numAllocations);
    comparePerformance<MyStruct67>(numAllocations);
    comparePerformance<MyStruct68>(numAllocations);
    comparePerformance<MyStruct69>(numAllocations);
    comparePerformance<MyStruct70>(numAllocations);
    comparePerformance<MyStruct71>(numAllocations);
    comparePerformance<MyStruct72>(numAllocations);
    comparePerformance<MyStruct73>(numAllocations);
    comparePerformance<MyStruct74>(numAllocations);
    comparePerformance<MyStruct75>(numAllocations);
    comparePerformance<MyStruct76>(numAllocations);
    comparePerformance<MyStruct77>(numAllocations);
    comparePerformance<MyStruct78>(numAllocations);
    comparePerformance<MyStruct79>(numAllocations);
    comparePerformance<MyStruct80>(numAllocations);
    comparePerformance<MyStruct81>(numAllocations);
    comparePerformance<MyStruct82>(numAllocations);
    comparePerformance<MyStruct83>(numAllocations);
    comparePerformance<MyStruct84>(numAllocations);
    comparePerformance<MyStruct85>(numAllocations);
    comparePerformance<MyStruct86>(numAllocations);
    comparePerformance<MyStruct87>(numAllocations);
    comparePerformance<MyStruct88>(numAllocations);
    comparePerformance<MyStruct89>(numAllocations);
    comparePerformance<MyStruct90>(numAllocations);
    comparePerformance<MyStruct91>(numAllocations);
    comparePerformance<MyStruct92>(numAllocations);
    comparePerformance<MyStruct93>(numAllocations);
    comparePerformance<MyStruct94>(numAllocations);
    comparePerformance<MyStruct95>(numAllocations);
    comparePerformance<MyStruct96>(numAllocations);
    comparePerformance<MyStruct97>(numAllocations);
    comparePerformance<MyStruct98>(numAllocations);
    comparePerformance<MyStruct99>(numAllocations);
    comparePerformance<MyStruct100>(numAllocations);
    comparePerformance<MyStruct101>(numAllocations);
    comparePerformance<MyStruct102>(numAllocations);
    comparePerformance<MyStruct103>(numAllocations);
    comparePerformance<MyStruct104>(numAllocations);
    comparePerformance<MyStruct105>(numAllocations);
    comparePerformance<MyStruct106>(numAllocations);
    comparePerformance<MyStruct107>(numAllocations);
    comparePerformance<MyStruct108>(numAllocations);
    comparePerformance<MyStruct109>(numAllocations);
    comparePerformance<MyStruct110>(numAllocations);
    comparePerformance<MyStruct111>(numAllocations);
    comparePerformance<MyStruct112>(numAllocations);
    comparePerformance<MyStruct113>(numAllocations);
    comparePerformance<MyStruct114>(numAllocations);
    comparePerformance<MyStruct115>(numAllocations);
    comparePerformance<MyStruct116>(numAllocations);
    comparePerformance<MyStruct117>(numAllocations);
    comparePerformance<MyStruct118>(numAllocations);
    comparePerformance<MyStruct119>(numAllocations);
    comparePerformance<MyStruct120>(numAllocations);
    comparePerformance<MyStruct121>(numAllocations);
    comparePerformance<MyStruct122>(numAllocations);
    comparePerformance<MyStruct123>(numAllocations);
    comparePerformance<MyStruct124>(numAllocations);
    comparePerformance<MyStruct125>(numAllocations);
    comparePerformance<MyStruct126>(numAllocations);
    comparePerformance<MyStruct127>(numAllocations);
    comparePerformance<MyStruct128>(numAllocations);
    comparePerformance<MyStruct129>(numAllocations);
    comparePerformance<MyStruct130>(numAllocations);
    comparePerformance<MyStruct131>(numAllocations);
    comparePerformance<MyStruct132>(numAllocations);
    comparePerformance<MyStruct133>(numAllocations);
    comparePerformance<MyStruct134>(numAllocations);
    comparePerformance<MyStruct135>(numAllocations);
    comparePerformance<MyStruct136>(numAllocations);
    comparePerformance<MyStruct137>(numAllocations);
    comparePerformance<MyStruct138>(numAllocations);
    comparePerformance<MyStruct139>(numAllocations);
    comparePerformance<MyStruct140>(numAllocations);
    comparePerformance<MyStruct141>(numAllocations);
    comparePerformance<MyStruct142>(numAllocations);
    comparePerformance<MyStruct143>(numAllocations);
    comparePerformance<MyStruct144>(numAllocations);
    comparePerformance<MyStruct145>(numAllocations);
    comparePerformance<MyStruct146>(numAllocations);
    comparePerformance<MyStruct147>(numAllocations);
    comparePerformance<MyStruct148>(numAllocations);
    comparePerformance<MyStruct149>(numAllocations);
    comparePerformance<MyStruct150>(numAllocations);
    comparePerformance<MyStruct151>(numAllocations);
    comparePerformance<MyStruct152>(numAllocations);
    comparePerformance<MyStruct153>(numAllocations);
    comparePerformance<MyStruct154>(numAllocations);
    comparePerformance<MyStruct155>(numAllocations);
    comparePerformance<MyStruct156>(numAllocations);
    comparePerformance<MyStruct157>(numAllocations);
    comparePerformance<MyStruct158>(numAllocations);
    comparePerformance<MyStruct159>(numAllocations);
    comparePerformance<MyStruct160>(numAllocations);
    comparePerformance<MyStruct161>(numAllocations);
    comparePerformance<MyStruct162>(numAllocations);
    comparePerformance<MyStruct163>(numAllocations);
    comparePerformance<MyStruct164>(numAllocations);
    comparePerformance<MyStruct165>(numAllocations);
    comparePerformance<MyStruct166>(numAllocations);
    comparePerformance<MyStruct167>(numAllocations);
    comparePerformance<MyStruct168>(numAllocations);
    comparePerformance<MyStruct169>(numAllocations);
    comparePerformance<MyStruct170>(numAllocations);
    comparePerformance<MyStruct171>(numAllocations);
    comparePerformance<MyStruct172>(numAllocations);
    comparePerformance<MyStruct173>(numAllocations);
    comparePerformance<MyStruct174>(numAllocations);
    comparePerformance<MyStruct175>(numAllocations);
    comparePerformance<MyStruct176>(numAllocations);
    comparePerformance<MyStruct177>(numAllocations);
    comparePerformance<MyStruct178>(numAllocations);
    comparePerformance<MyStruct179>(numAllocations);
    comparePerformance<MyStruct180>(numAllocations);
    comparePerformance<MyStruct181>(numAllocations);
    comparePerformance<MyStruct182>(numAllocations);
    comparePerformance<MyStruct183>(numAllocations);
    comparePerformance<MyStruct184>(numAllocations);
    comparePerformance<MyStruct185>(numAllocations);
    comparePerformance<MyStruct186>(numAllocations);
    comparePerformance<MyStruct187>(numAllocations);
    comparePerformance<MyStruct188>(numAllocations);
    comparePerformance<MyStruct189>(numAllocations);
    comparePerformance<MyStruct190>(numAllocations);
    comparePerformance<MyStruct191>(numAllocations);
    comparePerformance<MyStruct192>(numAllocations);
    comparePerformance<MyStruct193>(numAllocations);
    comparePerformance<MyStruct194>(numAllocations);
    comparePerformance<MyStruct195>(numAllocations);
    comparePerformance<MyStruct196>(numAllocations);
    comparePerformance<MyStruct197>(numAllocations);
    comparePerformance<MyStruct198>(numAllocations);
    comparePerformance<MyStruct199>(numAllocations);
    comparePerformance<MyStruct200>(numAllocations);
    comparePerformance<MyStruct201>(numAllocations);
    comparePerformance<MyStruct202>(numAllocations);
    comparePerformance<MyStruct203>(numAllocations);
    comparePerformance<MyStruct204>(numAllocations);
    comparePerformance<MyStruct205>(numAllocations);
    comparePerformance<MyStruct206>(numAllocations);
    comparePerformance<MyStruct207>(numAllocations);
    comparePerformance<MyStruct208>(numAllocations);
    comparePerformance<MyStruct209>(numAllocations);
    comparePerformance<MyStruct210>(numAllocations);
    comparePerformance<MyStruct211>(numAllocations);
    comparePerformance<MyStruct212>(numAllocations);
    comparePerformance<MyStruct213>(numAllocations);
    comparePerformance<MyStruct214>(numAllocations);
    comparePerformance<MyStruct215>(numAllocations);
    comparePerformance<MyStruct216>(numAllocations);
    comparePerformance<MyStruct217>(numAllocations);
    comparePerformance<MyStruct218>(numAllocations);
    comparePerformance<MyStruct219>(numAllocations);
    comparePerformance<MyStruct220>(numAllocations);
    comparePerformance<MyStruct221>(numAllocations);
    comparePerformance<MyStruct222>(numAllocations);
    comparePerformance<MyStruct223>(numAllocations);
    comparePerformance<MyStruct224>(numAllocations);
    comparePerformance<MyStruct225>(numAllocations);
    comparePerformance<MyStruct226>(numAllocations);
    comparePerformance<MyStruct227>(numAllocations);
    comparePerformance<MyStruct228>(numAllocations);
    comparePerformance<MyStruct229>(numAllocations);
    comparePerformance<MyStruct230>(numAllocations);
    comparePerformance<MyStruct231>(numAllocations);
    comparePerformance<MyStruct232>(numAllocations);
    comparePerformance<MyStruct233>(numAllocations);
    comparePerformance<MyStruct234>(numAllocations);
    comparePerformance<MyStruct235>(numAllocations);
    comparePerformance<MyStruct236>(numAllocations);
    comparePerformance<MyStruct237>(numAllocations);
    comparePerformance<MyStruct238>(numAllocations);
    comparePerformance<MyStruct239>(numAllocations);
    comparePerformance<MyStruct240>(numAllocations);
    comparePerformance<MyStruct241>(numAllocations);
    comparePerformance<MyStruct242>(numAllocations);
    comparePerformance<MyStruct243>(numAllocations);
    comparePerformance<MyStruct244>(numAllocations);
    comparePerformance<MyStruct245>(numAllocations);
    comparePerformance<MyStruct246>(numAllocations);
    comparePerformance<MyStruct247>(numAllocations);
    comparePerformance<MyStruct248>(numAllocations);
    comparePerformance<MyStruct249>(numAllocations);
    comparePerformance<MyStruct250>(numAllocations);
    comparePerformance<MyStruct251>(numAllocations);
    comparePerformance<MyStruct252>(numAllocations);
    comparePerformance<MyStruct253>(numAllocations);
    comparePerformance<MyStruct254>(numAllocations);
    comparePerformance<MyStruct255>(numAllocations);
}